## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -pe smp 1
#$ -r yes
#$ -l mem_requested=30G
#$ -N generate_expression_file_NK_R
#$ -o stdout_generate_expression_file_NK_R
#$ -e stderr_generate_expression_file_NK_R
#$ -t 1-22

cd $SGE_O_WORKDIR

i=${SGE_TASK_ID};

Rscript="/share/ScratchGeneral/angxue/software/miniconda3/envs/r_env/bin/Rscript"

mkdir -p NK_R

# touch ./NK_R/chr${i}_generate_expression_file_NK_R.log
# > ./NK_R/chr${i}_generate_expression_file_NK_R.log

$Rscript --vanilla generate_expression_file.R ${i} NK_R 





