## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -pe smp 1
#$ -r yes
#$ -l mem_requested=30G
#$ -N generate_expression_file_B_MEM
#$ -o stdout_generate_expression_file_B_MEM
#$ -e stderr_generate_expression_file_B_MEM
#$ -t 1-22

cd $SGE_O_WORKDIR

i=${SGE_TASK_ID};

Rscript="/share/ScratchGeneral/angxue/software/miniconda3/envs/r_env/bin/Rscript"

mkdir -p B_MEM

# touch ./B_MEM/chr${i}_generate_expression_file_B_MEM.log
# > ./B_MEM/chr${i}_generate_expression_file_B_MEM.log

$Rscript --vanilla generate_expression_file.R ${i} B_MEM 





