## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -pe smp 1
#$ -r yes
#$ -l mem_requested=30G
#$ -N generate_expression_file_DC
#$ -o stdout_generate_expression_file_DC
#$ -e stderr_generate_expression_file_DC
#$ -t 1-22

cd $SGE_O_WORKDIR

i=${SGE_TASK_ID};

Rscript="/share/ScratchGeneral/angxue/software/miniconda3/envs/r_env/bin/Rscript"

mkdir -p DC

# touch ./DC/chr${i}_generate_expression_file_DC.log
# > ./DC/chr${i}_generate_expression_file_DC.log

$Rscript --vanilla generate_expression_file.R ${i} DC 





