## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -pe smp 1
#$ -r yes
#$ -l mem_requested=30G
#$ -N generate_expression_file_Mono_NC
#$ -o stdout_generate_expression_file_Mono_NC
#$ -e stderr_generate_expression_file_Mono_NC
#$ -t 1-22

cd $SGE_O_WORKDIR

i=${SGE_TASK_ID};

Rscript="/share/ScratchGeneral/angxue/software/miniconda3/envs/r_env/bin/Rscript"

mkdir -p Mono_NC

# touch ./Mono_NC/chr${i}_generate_expression_file_Mono_NC.log
# > ./Mono_NC/chr${i}_generate_expression_file_Mono_NC.log

$Rscript --vanilla generate_expression_file.R ${i} Mono_NC 





